### ISSUE TITLE
Run lighthouse with `view` option to immediately open the HTML report in your browser

### ISSUE THREAD

**Issue by kevinfarrugia** [addyosmani/webpack-lighthouse-plugin#14]
When using Lighthouse in the CLI, it is possible to view the HTML report directly in the browser using `--view`. Is it possible to include the same functionality on this plugin?

**Comment by ev1stensberg** [comment]
Depends on which type of module lighthouse exposes:
https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#using-programmatically

It should work, at least from a initial point of view. Seems to be docs missing to add lighthouse flags instead of chrome flags though.. @patrickhulce any input? 

You could create your own config to audit with though. I don't think we support that, so let's wait to hear from Patrick.

**Comment by patrickhulce** [comment]
Lighthouse is unifying [many of the CLI flags](https://github.com/GoogleChrome/lighthouse/blob/711ca6e50f5cf40ba04d878d543a3f4e55c7453a/typings/externs.d.ts#L43-L57) to be available from node module in v3, but `--view` isn't one of them. It should be fairly easy to implement on the plugin side though, it really comes down to [just a few lines](https://github.com/GoogleChrome/lighthouse/blob/711ca6e50f5cf40ba04d878d543a3f4e55c7453a/lighthouse-cli/run.js#L134-L135)

**Comment by kevinfarrugia** [comment]
OK understood. Does it make sense to wait for v3 then?

**Comment by evenstensberg** [comment]
I think this is fixed, comment if not.
